#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80

sudo apt-get update
sudo apt-get -y install nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index
echo -e "Hello World!"

# Restarting nginx
sudo service nginx start