#!/usr/bin/env bash
# this script display to infinity and beyond

pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -z "$pid" ]; then
    echo "To infinity and beyond"
else
    kill "$pid"
    echo "Terminated"
fi

