#!/usr/bin/env bash
#print 20 times

n=school
if [ -e $n ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $n ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $n ]; then
    echo "school is a regular file"
fi

