#!/usr/bin/env bash
#uses ssh to connect
passphrase="betty"
private_key_file="school"
ssh-keygen -t rsa -b 4096 -f "$private_key_file" -N "$passphrase"
echo "RSA key pair created with passphrase '$passphrase' and saved as '$private_key_file'"
